-- PostgreSQL Schema: Person (Target for MongoDB -> PostgreSQL migration)
-- 3NF Normalized from MongoDB nested document with 3-level nesting
-- Generated by SMEL test script: person_mongo_to_pg_minibeispiel.smel
-- Tests 3-level deep nesting: person.employment.company.address

-- Table 1: person (main entity)
-- FLATTEN person.name → vorname, nachname
-- CAST age TO Integer
CREATE TABLE person (
    person_id VARCHAR(255) PRIMARY KEY,
    vorname VARCHAR(255),
    nachname VARCHAR(255),
    age INTEGER
);

-- Table 2: address (extracted from person.address - level 1)
-- UNNEST person.address:street,city AS address
CREATE TABLE address (
    address_id VARCHAR(255) PRIMARY KEY,
    person_id VARCHAR(255) NOT NULL REFERENCES person(person_id),
    street VARCHAR(255),
    city VARCHAR(255)
);

-- Table 3: employment (extracted from person.employment - level 1)
-- UNNEST person.employment:position, company{...} AS employment
CREATE TABLE employment (
    employment_id VARCHAR(255) PRIMARY KEY,
    person_id VARCHAR(255) NOT NULL REFERENCES person(person_id),
    position VARCHAR(255)
);

-- Table 4: company (extracted from employment.company - level 2)
-- UNNEST employment.company:name, address{...} AS company
CREATE TABLE company (
    company_id VARCHAR(255) PRIMARY KEY,
    employment_id VARCHAR(255) NOT NULL REFERENCES employment(employment_id),
    name VARCHAR(255)
);

-- Table 5: company_address (extracted from company.address - level 3)
-- UNNEST company.address:street,city AS company_address
-- Demonstrates 3-level deep nesting: person → employment → company → address
CREATE TABLE company_address (
    company_address_id VARCHAR(255) PRIMARY KEY,
    company_id VARCHAR(255) NOT NULL REFERENCES company(company_id),
    street VARCHAR(255),
    city VARCHAR(255)
);

-- Table 6: person_tag (1:N array relationship)
-- SPLIT person INTO person(...), person_tag(person_id, tags)
-- UNWIND person_tag.tags
-- RENAME tags TO tag_value
CREATE TABLE person_tag (
    person_tag_id VARCHAR(255) PRIMARY KEY,
    person_id VARCHAR(255) NOT NULL REFERENCES person(person_id),
    tag_value VARCHAR(255)
);

-- Table 7: person_knows (M:N self-reference join table)
-- SPLIT person INTO person(...), person_knows(person_id, knows)
-- UNWIND person_knows.knows
-- RENAME knows TO knows_person_id
-- Composite primary key (person_id, knows_person_id)
CREATE TABLE person_knows (
    person_id VARCHAR(255) NOT NULL REFERENCES person(person_id),
    knows_person_id VARCHAR(255) NOT NULL REFERENCES person(person_id),
    PRIMARY KEY (person_id, knows_person_id)
);
